### ISSUE TITLE
Render + FastAPI + Docker(+DB)環境構築

### ISSUE THREAD

**Issue by balle-mech** [balle-mech/shooting-game-api#1]
**Render + FastAPI + Docker環境構築**

ユーザーはRender + FastAPI + Dockerを使った開発環境構築方法を尋ねています。手順としては、FastAPIアプリを作成し、Dockerfileを記述、docker-composeを使ってローカル開発環境を設定します。その後、Renderにデプロイするために、GitHubにプッシュし、Renderサービスをリンク、Dockerビルドコマンドを設定します。さらに、ポートと環境変数の設定、ヘルスチェック、---reloadオプション、render.yamlの追加設定を進めます。

以下の手順で、FastAPI アプリを Docker コンテナ化し、Render.com 上で自動デプロイできる開発環境を構築します。

---

## 1. プロジェクト構成例

```
my-fastapi-app/
├── app/
│   └── main.py
├── requirements.txt
├── Dockerfile
└── docker-compose.yml      # ローカル開発用（任意）
```

---

## 2. FastAPI アプリの準備

まず、最小限の FastAPI アプリを `app/main.py` に用意します。

```python
# app/main.py
from fastapi import FastAPI

app = FastAPI()

@app.get("/")
async def root():
    return {"message": "Hello, Render + FastAPI + Docker!"}
```

依存パッケージは `requirements.txt` に記述：

```
fastapi
uvicorn[standard]
```

---

## 3. Dockerfile の作成

Render.com 上で Docker 環境を使う場合、以下のような `Dockerfile` をプロジェクト直下に置きます。
参考：https://fastapi.tiangolo.com/ja/deployment/docker/#dockerfile

```Dockerfile
# ベースイメージに公式の Python スリム版を使用
FROM python:3.11-slim

# ワーキングディレクトリを設定
WORKDIR /app

# 依存ファイルを先にコピーしてキャッシュ利用
COPY requirements.txt .

# 依存インストール
RUN pip install --no-cache-dir -r requirements.txt

# アプリケーションコードをコピー
COPY app ./app

# コンテナ起動時に実行するコマンド
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
```

* `EXPOSE` は明示不要（Render はポートバインディングを自動検出します） ([[FastAPI](https://fastapi.tiangolo.com/deployment/docker/?utm_source=chatgpt.com)][1])

---

## 4. （任意）docker-compose.yml でローカル開発を快適に

ホットリロード付きで動かしたい場合などに、ローカルで `docker-compose up` できる設定例：

```yaml
version: '3.8'
services:
  api:
    build: .
    volumes:
      - ./app:/app/app       # ホストのコードをマウント
    ports:
      - "8000:8000"
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload
```

これで `http://localhost:8000` にアクセスするとリアルタイム反映されます。

---

## 5. GitHub（または GitLab/Bitbucket）へコードを Push

1. 新規リポジトリを作成
2. `git push -u origin main` などでソースをアップロード

---

## 6. Render.com でのデプロイ設定

1. **New → Web Service** をクリック
2. **Environment** で **Docker** を選択
3. リポジトリとブランチを指定
4. **Advanced** セクションで必要に応じて以下を確認／設定

   * **Build Command**：通常は空欄で OK（[Render](https://render.com/docs/deploy-fastapi?utm_source=chatgpt.com) が自動検出）
   * **Start Command**：`uvicorn app.main:app --host 0.0.0.0 --port $PORT` ([Render][2])
   * **Environment Variables**：`PORT=8000` を設定（Render 側で自動的に渡されます）
5. **Create Web Service** を押すと自動でビルド＆デプロイが始まります

---

## 7. （任意）render.yaml を使ったインフラ as Code

リポジトリ直下に `render.yaml` を置くと、Web サービス設定をコード管理できます。

```yaml
services:
  - type: web
    name: my-fastapi-app
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    buildCommand: ""
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
```

---

### 補足

* **ローカル開発** では `docker-compose up`
* **本番・ステージング** は [Render](https://render.com/docs/deploy-fastapi?utm_source=chatgpt.com).com 側で自動ビルド＆デプロイ
* Render の **Health Check** や **Auto Deploy**（Git プッシュ検知）も活用すると楽です ([Render][2])

[1]: https://fastapi.tiangolo.com/deployment/docker/?utm_source=chatgpt.com "FastAPI in Containers - Docker"
[2]: https://render.com/docs/deploy-fastapi?utm_source=chatgpt.com "Deploy a FastAPI App – Render Docs"
